### PR TITLE
Fix strong mode errors

### LINKED ISSUE #56: Strong mode errors
initialize contains some code that is not strong. Here is a report  from analyzer 1.24.0:

```
dartanalyzer --strong lib/
Analyzing lib...
  error • The method 'map' isn't defined for the class 'Object' at lib/build/initializer_plugin.dart:307:22 • undefined_method
  error • Invalid override. The type of 'LibraryIdentifier.==' ('(LibraryIdentifier) → bool') isn't a subtype of 'Object.==' ('(dynamic) → bool') at lib/src/initializer.dart:44:3 • strong_mode_invalid_method_override
  error • The getter 'metadata' isn't defined for the class 'AstNode' at lib/transformer.dart:274:38 • undefined_getter
  error • The getter 'metadata' isn't defined for the class 'AstNode' at lib/transformer.dart:276:24 • undefined_getter
  error • The getter 'evaluationResult' isn't defined for the class 'PropertyInducingElement' at lib/transformer.dart:286:42 • undefined_getter
  hint • The type of '_root' can't be inferred because of the use of the instance getter 'rootLibrary' at lib/src/mirror_loader.dart:11:45 • strong_mode_top_level_instance_getter
  hint • The type of '_libs' can't be inferred because of the use of the instance getter 'libraries' at lib/src/mirror_loader.dart:12:37 • strong_mode_top_level_instance_getter
5 errors and 2 hints found.
```

### PR DESCRIPTION
**Pull request by kirbyfan64**
Closes #56.

### CODE REVIEW

**Comment by kirbyfan64** [comment]
*CLA recheck comment*

File: lib/build/initializer_plugin.dart [hunk 1]
```diff
@@ -302,7 +302,7 @@ class DefaultInitializerPlugin implements InitializerPlugin {
         object.toIntValue() ??
         object.toStringValue();
     if (value == null) {
-      value = object.toListValue();
+      List value = object.toListValue();
```
Comment (jakemac53) [inline lib/build/initializer_plugin.dart]: nit: rename this so as not to shadow the other local variable (`list` would be consistent with `map` below)

File: lib/src/mirror_loader.dart [hunk 2]
```diff
@@ -8,8 +8,8 @@ import 'dart:mirrors';
 import 'package:path/path.dart' as path;
 import 'package:initialize/initialize.dart';
 
-final _root = currentMirrorSystem().isolate.rootLibrary;
-final _libs = currentMirrorSystem().libraries;
+final LibraryMirror _root = currentMirrorSystem().isolate.rootLibrary;
```
Comment (jakemac53) [inline lib/src/mirror_loader.dart]: These explicit types shouldn't be necessary, were these providing a strong mode error?

Comment (kirbyfan64) [reply lib/src/mirror_loader.dart]: I get:

```
  hint • The type of '_root' can't be inferred because of the use of the instance getter 'rootLibrary' at lib/src/mirror_loader.dart:12:45 • strong_mode_top_level_instance_getter
```

**Comment by kirbyfan64** [comment]
@jakemac53 Done.

File: lib/src/mirror_loader.dart (hunk 2 above)
Comment (jakemac53) [reply lib/src/mirror_loader.dart]: Ah ok  ya I forgot top level things don't have quite as nice inference :(
